name: firebase_anon_bug
description: "This flutter project accompanies the `firebase` folder to reproduce the bug listed here: https://github.com/firebase/flutterfire/issues/12473"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.26.0 # needed by other Firebase plugins
  cloud_functions: ^4.6.9 # used for calling Firebase Functions
  firebase_auth: ^4.17.9 # account auth via Firebase

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
