name: firebase_anon_bug
description: "This flutter project accompanies the `firebase` folder to reproduce the bug listed here: https://github.com/firebase/flutterfire/issues/12473"

# Prevent publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.2.0 # needed by other Firebase plugins
  cloud_functions: ^5.0.3 # used for calling Firebase Functions
  firebase_auth: ^5.1.2 # account auth via Firebase
  flutter_riverpod: ^2.5.1 # state mangement

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
